# Generated by Django 5.0.7 on 2024-07-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarBrand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand_name", models.CharField(max_length=128)),
                ("brand_popularity_score", models.IntegerField()),
                ("Brand_Accesibility_Score", models.IntegerField()),
                ("Service_Quality_Score", models.IntegerField()),
                ("Maintainence_Spares_Score", models.IntegerField()),
                ("Reliability_Score", models.IntegerField()),
                ("Resale_Value_Score", models.IntegerField()),
                ("Vehicle_Characteristic", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="CarType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Car_Name", models.CharField(max_length=128)),
                ("Price_Range", models.FloatField()),
                ("Mileage", models.FloatField()),
                ("Power", models.FloatField()),
                ("Transmission", models.FloatField()),
                ("Vehicle_Type", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="CarVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("variant_name", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
