# Generated by Django 5.0.7 on 2024-07-29 16:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dekho", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carbrand",
            name="Vehicle_Characteristic",
        ),
    ]
