# Generated by Django 5.0.7 on 2024-07-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dekho", "0002_remove_carbrand_vehicle_characteristic"),
    ]

    operations = [
        migrations.AddField(
            model_name="carbrand",
            name="Safety_Score",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
