# Generated by Django 5.0.7 on 2024-07-31 03:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dekho", "0003_carbrand_safety_score"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartype",
            name="Mileage",
        ),
        migrations.RemoveField(
            model_name="cartype",
            name="Power",
        ),
        migrations.RemoveField(
            model_name="cartype",
            name="Transmission",
        ),
        migrations.AddField(
            model_name="carvariant",
            name="Mileage",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="carvariant",
            name="Power",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="carvariant",
            name="Transmission",
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
